### ISSUE TITLE
Get direction from the onSwipedOut event

### ISSUE THREAD

**Issue by EtgarSH** [wix/react-native-swipe-view#1]
`<SwipeView
        changeOpacity
        removeViewOnSwipedOut
        onSwipedOut={(direction) => {
          if (direction === 'right') {
            // Do something
          } else if (direction === 'left') {
            // Do something
          }
        }}
      >`

But the RCTDirectEventBlock isn't being called with the direction, so that we cannot use the direction property in the JS.

I saw in the Objective C that the code looks like:
`_onSwipedOut(@{@"direction": directionString});
           self.onSwipedOut = nil;
`
But even `direction.direction` (in the upper code) doesn't work.

**Comment by EtgarSH** [comment]
OK, we have found a solution - I should have used `data.nativeEvent.direction`.
The instructions in the README were missing this example.

**Comment by artald** [comment]
Cool 👍

I want to say that that's how RCTDirectEventBlock is supposed to work, but I don't really remember since we're currently not using the "direction" feature.
